[package]
name = "six-degrees-bot"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["cargo"] }
itertools = "0.13.0"
nostr = "0.34.1"
nostr-sdk = { version = "0.34.0", features = ["ndb"] }
petgraph = "0.6.5"
tokio = "1.40.0"
